apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    app: prometheus
    purpose: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      purpose: ecommerce
  template:
    metadata:
      labels:
        app: prometheus
        purpose: ecommerce
    spec:
      containers:
      - name: ecommerce
        image: prom/prometheus
        volumeMounts:
          - name: config-volume
            mountPath: /etc/prometheus/prometheus.yml
            subPath: prometheus.yml
        ports:
        - containerPort: 9090
      volumes:
        - name: config-volume
          configMap:
           name: ecommerce
---
kind: Service
apiVersion: v1
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
    purpose: ecommerce
  ports:
  - name: promui
    protocol: TCP
    port: 9090
    targetPort: 9090
